Add .data JSON and YML file formats and move devnet data to /deprecated
commercionetwork/chains pull request #19
Opened 2023-11-27 13:09 UTC by lmc-mint

* To use the chain information from `.data` files as variables in the ansible playbook, we need to integrate other `.data` files formats such as `JSON` and `YML`.

* Move devnet data to `deprecated` directory

2023-11-27 14:27 UTC, marcotradenet requested changes

2023-11-27 14:27 UTC, marcotradenet commented on commercio-testnet11k/.data.json
> +  "Name": " testnet11k",
There is an error here: a white space before name value

2023-11-27 14:27 UTC, marcotradenet commented on commercio-testnet11k/.data.yml
> +Name: ' testnet11k'
Same errore here

2023-11-27 16:03 UTC, lmc-mint commented on commercio-testnet11k/.data.yml
> +Name: ' testnet11k'
Corrected

2023-11-27 16:13 UTC, marcotradenet commented on commercio-3/.data.json
> +}
Maybe it is better to add rpcs server here, so you can use it in the chain installer tool. Something like this
```
...
   "rpc_servers": "rpc-mainnet.commercio.network:80,rpc2-mainnet.commercio.network:80"
}
```

or 

```
...
   "rpc_servers": [
       "rpc-mainnet.commercio.network:80",
       "rpc2-mainnet.commercio.network:80"
   ]
}
```

2023-11-28 10:37 UTC, marcotradenet approved these changes

2023-11-28 10:38 UTC, merged